# https://rust-lang.github.io/rustfmt/
format_strings                = true
blank_lines_lower_bound       = 0
blank_lines_upper_bound       = 1
chain_width                   = 80
comment_width                 = 95
empty_item_single_line        = true
enum_discrim_align_threshold  = 20
fn_args_layout                = "compressed"
fn_single_line                = true
format_code_in_doc_comments   = true
indent_style                  = "Visual"
max_width                     = 100
normalize_comments            = true
overflow_delimited_expr       = true
reorder_impl_items            = true
single_line_if_else_max_width = 90
format_macro_matchers         = true
format_macro_bodies           = true
struct_field_align_threshold  = 20
struct_lit_single_line        = true
struct_lit_width              = 20
struct_variant_width          = 40
use_small_heuristics          = "Max"
where_single_line             = true
wrap_comments                 = true
